module.exports = {
  SYMPTOM_CHECK: "SYMPTOM_CHECK",
  APPOINTMENT_QUERY: "APPOINTMENT_QUERY",
  BILLING_QUERY: "BILLING_QUERY",
  DOCTOR_SCHEDULE: "DOCTOR_SCHEDULE",
  ADMIN_ANALYTICS: "ADMIN_ANALYTICS",
  GENERAL_HELP: "GENERAL_HELP",
};
